Repository pyvec/naucse.python.cz, pull requests merged in 2018-04, with the labels that each got.

#366 Synchronizace s Pyladies.cz
  runs/2018/pyladies-ostrava-jaro/info.yml
Labels: beginners-course

#362 Rendering courses from forks and content fragments caching
  .gitignore
  .travis.yml
  README.md
  naucse/__init__.py
  naucse/cli.py
  naucse/freezer.py
  naucse/models.py
  naucse/routes.py
  naucse/templates.py
  naucse/templates/_base.html
  naucse/templates/_base_course.html
  naucse/templates/_using_default_page.html
  naucse/templates/backpage.html
  naucse/templates/content/backpage.html
  naucse/templates/content/course.html
  naucse/templates/content/course_calendar.html
  naucse/templates/content/coverpage.html
  naucse/templates/course.html
  naucse/templates/course_calendar.html
  naucse/templates/course_list.html
  naucse/templates/coverpage.html
  naucse/templates/error_in_fork.html
  naucse/templates/lesson.html
  naucse/templates/run_list.html
  naucse/templates/solution.html
  naucse/urlconverters.py
  naucse/utils/forks.py
  naucse/utils/links.py
  naucse/utils/models.py
  naucse/utils/routes.py
  pytest.ini
  requirements.txt
  test_naucse/fixtures/test_content/lessons/.gitkeep
  test_naucse/test_forks.py
  test_naucse/test_routes_utils.py
  test_requirements.txt
Labels: code, enhancement, travis

#370 Micropy workshop additions
  lessons/micropython/mini-workshop/index.md
  lessons/micropython/mini-workshop/organizers.md
  lessons/micropython/mini-workshop/static/boot.py
Labels: content

#400 Use correct default in MetaInfo.branch
  naucse/models.py
Labels: code, forks
